# Generated by Django 3.2.9 on 2021-12-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('ShortLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.shortlink')),
            ],
        ),
    ]
