# Generated by Django 3.2.9 on 2021-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='linkId',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
