# Generated by Django 3.2.9 on 2021-12-09 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_alter_shortlink_linkid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='ShortLink',
            new_name='shortlink',
        ),
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
